version: "3.9"

services:
  app:
    build: .
    container_name: trade-bet-app
    restart: always
    env_file: .env
    ports:
      - "${PORT}:4018"
    depends_on:
      - mysql
      - mysql_read
      - redis
      - influxdb
    environment:
      DB_HOST: mysql
      DB_HOST_READ: mysql_read
      REDIS_HOST: redis
      INFLUXDB_URL: http://influxdb:8086

  mysql:
    image: mysql:8
    container_name: mysql_write
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}           # create your app user
      MYSQL_PASSWORD: ${DB_PASSWORD}   # same password for read/write
    ports:
      - "3306:3306"
    command: --server-id=1 --log-bin=mysql-bin
    volumes:
      - mysql_write_data:/var/lib/mysql

  mysql_read:
    image: mysql:8
    container_name: mysql_read
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}           # same user
      MYSQL_PASSWORD: ${DB_PASSWORD}   # same password
    ports:
      - "3307:3306"
    command: --server-id=2 --log-bin=mysql-bin
    volumes:
      - mysql_read_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    command: >
      redis-server
      --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    restart: always
    ports:
      - "8086:8086"
    # environment:
    #   DOCKER_INFLUXDB_INIT_MODE: setup
    #   DOCKER_INFLUXDB_INIT_USERNAME: admin
    #   DOCKER_INFLUXDB_INIT_PASSWORD: admin123
    #   DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_ORG}
    #   DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_BUCKET}
    #   DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_TOKEN}
    volumes:
      - influx_data:/var/lib/influxdb2

volumes:
  mysql_write_data:
  mysql_read_data:
  redis_data:
  influx_data: