deploy:
  stage: deploy
  before_script:
    - mkdir -p ~/.ssh
    - echo "$test_pem" > ~/.ssh/test.pem
    - chmod 600 ~/.ssh/test.pem
  script:
    - ssh -o StrictHostKeyChecking=no -i ~/.ssh/test.pem ubuntu@3.111.32.9  "cd /home/ubuntu && bash mega.sh"